name: CI/CD Pipeline

on:
  push:
    branches: [develop, master]

jobs:
  # Этот job запускается ТОЛЬКО для develop
  code-check:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'
          
      - name: Run Black 
        run: |
          pip install black==23.12.0
          black .


