name: Develop CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.5'
    
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest
        
    - name: Run tests
      run: pytest tests/ -v
      env:
        PYTHONPATH: ${{ github.workspace }}
