name: CI Pipeline (Develop)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.5'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run tests
      run: |
        PYTHONPATH=. pytest tests/ -v
        
    - name: Check code style
      run: |
        pip install flake8
        flake8 bot/ --count --show-source --statistics --max-line-length=120
